import climatelearn.learning.regression.deap_GP
import climatelearn.learning.regression.pybrain_MP
import climatelearn.learning.regression.weka_regr_MP
import climatelearn.learning.regression.keras_ANN